apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server-deployment
  template:
    metadata:
      labels:
        component: server-deployment
    spec:
      containers:
      - name: server-deployment
        image: stephengrider/multi-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGUSER
            value: postgres
          - name: PGDATABASE
            value: postgres
          - name: PGPORT
            value: "5432"
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: pgpassword
